#define KEY_ERROR_OR_BUFFER_OVERRUN 0x00
#define SELF_TEST_PASSED 0xAA
#define ECHO 0xEE
#define KEYB_ACK 0xFA
#define SELF_TEST_FAILED 0xFC
#define SELF_TEST_FAILED_OTHER 0xFD
#define RESEND 0xFE
#define KEY_ERROR_OR_BUFFER_OVERRUN_OTHER 0xFF