#include <kernel/hal/managers/irqcmanager.hpp>
#include <kernel/drivers/interrupts.hpp>

#define DECLARE_IRQ_HANDLER(n)            \
    [[gnu::interrupt]]                    \
    static void irq_handler_##n(interrupt_frame*) { \
        hal::IRQControllerManager::get().irq_handler(n); \
    }

#define DECLARE_IRQ_HANDLERS() \
    DECLARE_IRQ_HANDLER(0)   \
    DECLARE_IRQ_HANDLER(1)   \
    DECLARE_IRQ_HANDLER(2)   \
    DECLARE_IRQ_HANDLER(3)   \
    DECLARE_IRQ_HANDLER(4)   \
    DECLARE_IRQ_HANDLER(5)   \
    DECLARE_IRQ_HANDLER(6)   \
    DECLARE_IRQ_HANDLER(7)   \
    DECLARE_IRQ_HANDLER(8)   \
    DECLARE_IRQ_HANDLER(9)   \
    DECLARE_IRQ_HANDLER(10)  \
    DECLARE_IRQ_HANDLER(11)  \
    DECLARE_IRQ_HANDLER(12)  \
    DECLARE_IRQ_HANDLER(13)  \
    DECLARE_IRQ_HANDLER(14)  \
    DECLARE_IRQ_HANDLER(15)  \
    DECLARE_IRQ_HANDLER(16)  \
    DECLARE_IRQ_HANDLER(17)  \
    DECLARE_IRQ_HANDLER(18)  \
    DECLARE_IRQ_HANDLER(19)  \
    DECLARE_IRQ_HANDLER(20)  \
    DECLARE_IRQ_HANDLER(21)  \
    DECLARE_IRQ_HANDLER(22)  \
    DECLARE_IRQ_HANDLER(23)  \
    DECLARE_IRQ_HANDLER(24)  \
    DECLARE_IRQ_HANDLER(25)  \
    DECLARE_IRQ_HANDLER(26)  \
    DECLARE_IRQ_HANDLER(27)  \
    DECLARE_IRQ_HANDLER(28)  \
    DECLARE_IRQ_HANDLER(29)  \
    DECLARE_IRQ_HANDLER(30)  \
    DECLARE_IRQ_HANDLER(31)  \
    DECLARE_IRQ_HANDLER(32)  \
    DECLARE_IRQ_HANDLER(33)  \
    DECLARE_IRQ_HANDLER(34)  \
    DECLARE_IRQ_HANDLER(35)  \
    DECLARE_IRQ_HANDLER(36)  \
    DECLARE_IRQ_HANDLER(37)  \
    DECLARE_IRQ_HANDLER(38)  \
    DECLARE_IRQ_HANDLER(39)  \
    DECLARE_IRQ_HANDLER(40)  \
    DECLARE_IRQ_HANDLER(41)  \
    DECLARE_IRQ_HANDLER(42)  \
    DECLARE_IRQ_HANDLER(43)  \
    DECLARE_IRQ_HANDLER(44)  \
    DECLARE_IRQ_HANDLER(45)  \
    DECLARE_IRQ_HANDLER(46)  \
    DECLARE_IRQ_HANDLER(47)  \
    DECLARE_IRQ_HANDLER(48)  \
    DECLARE_IRQ_HANDLER(49)  \
    DECLARE_IRQ_HANDLER(50)  \
    DECLARE_IRQ_HANDLER(51)  \
    DECLARE_IRQ_HANDLER(52)  \
    DECLARE_IRQ_HANDLER(53)  \
    DECLARE_IRQ_HANDLER(54)  \
    DECLARE_IRQ_HANDLER(55)  \
    DECLARE_IRQ_HANDLER(56)  \
    DECLARE_IRQ_HANDLER(57)  \
    DECLARE_IRQ_HANDLER(58)  \
    DECLARE_IRQ_HANDLER(59)  \
    DECLARE_IRQ_HANDLER(60)  \
    DECLARE_IRQ_HANDLER(61)  \
    DECLARE_IRQ_HANDLER(62)  \
    DECLARE_IRQ_HANDLER(63)  \
    DECLARE_IRQ_HANDLER(64)  \
    DECLARE_IRQ_HANDLER(65)  \
    DECLARE_IRQ_HANDLER(66)  \
    DECLARE_IRQ_HANDLER(67)  \
    DECLARE_IRQ_HANDLER(68)  \
    DECLARE_IRQ_HANDLER(69)  \
    DECLARE_IRQ_HANDLER(70)  \
    DECLARE_IRQ_HANDLER(71)  \
    DECLARE_IRQ_HANDLER(72)  \
    DECLARE_IRQ_HANDLER(73)  \
    DECLARE_IRQ_HANDLER(74)  \
    DECLARE_IRQ_HANDLER(75)  \
    DECLARE_IRQ_HANDLER(76)  \
    DECLARE_IRQ_HANDLER(77)  \
    DECLARE_IRQ_HANDLER(78)  \
    DECLARE_IRQ_HANDLER(79)  \
	DECLARE_IRQ_HANDLER(80)  \
    DECLARE_IRQ_HANDLER(81)  \
    DECLARE_IRQ_HANDLER(82)  \
    DECLARE_IRQ_HANDLER(83)  \
    DECLARE_IRQ_HANDLER(84)  \
    DECLARE_IRQ_HANDLER(85)  \
    DECLARE_IRQ_HANDLER(86)  \
    DECLARE_IRQ_HANDLER(87)  \
    DECLARE_IRQ_HANDLER(88)  \
    DECLARE_IRQ_HANDLER(89)  \
    DECLARE_IRQ_HANDLER(90)  \
    DECLARE_IRQ_HANDLER(91)  \
    DECLARE_IRQ_HANDLER(92)  \
    DECLARE_IRQ_HANDLER(93)  \
    DECLARE_IRQ_HANDLER(94)  \
    DECLARE_IRQ_HANDLER(95)  \
    DECLARE_IRQ_HANDLER(97)  \
    DECLARE_IRQ_HANDLER(98)  \
    DECLARE_IRQ_HANDLER(99)  \
    DECLARE_IRQ_HANDLER(100) \
    DECLARE_IRQ_HANDLER(101) \
    DECLARE_IRQ_HANDLER(102) \
    DECLARE_IRQ_HANDLER(103) \
    DECLARE_IRQ_HANDLER(104) \
    DECLARE_IRQ_HANDLER(105) \
    DECLARE_IRQ_HANDLER(106) \
    DECLARE_IRQ_HANDLER(107) \
    DECLARE_IRQ_HANDLER(108) \
    DECLARE_IRQ_HANDLER(109) \
    DECLARE_IRQ_HANDLER(110) \
    DECLARE_IRQ_HANDLER(111) \
    DECLARE_IRQ_HANDLER(112) \
    DECLARE_IRQ_HANDLER(113) \
    DECLARE_IRQ_HANDLER(114) \
    DECLARE_IRQ_HANDLER(115) \
    DECLARE_IRQ_HANDLER(116) \
    DECLARE_IRQ_HANDLER(117) \
    DECLARE_IRQ_HANDLER(118) \
    DECLARE_IRQ_HANDLER(119) \
    DECLARE_IRQ_HANDLER(120) \
    DECLARE_IRQ_HANDLER(121) \
    DECLARE_IRQ_HANDLER(122) \
    DECLARE_IRQ_HANDLER(123) \
    DECLARE_IRQ_HANDLER(124) \
    DECLARE_IRQ_HANDLER(125) \
    DECLARE_IRQ_HANDLER(126) \
    DECLARE_IRQ_HANDLER(127) \
    DECLARE_IRQ_HANDLER(128) \
    DECLARE_IRQ_HANDLER(129) \
    DECLARE_IRQ_HANDLER(130) \
    DECLARE_IRQ_HANDLER(131) \
    DECLARE_IRQ_HANDLER(132) \
    DECLARE_IRQ_HANDLER(133) \
    DECLARE_IRQ_HANDLER(134) \
    DECLARE_IRQ_HANDLER(135) \
    DECLARE_IRQ_HANDLER(136) \
    DECLARE_IRQ_HANDLER(137) \
    DECLARE_IRQ_HANDLER(138) \
    DECLARE_IRQ_HANDLER(139) \
    DECLARE_IRQ_HANDLER(140) \
    DECLARE_IRQ_HANDLER(141) \
    DECLARE_IRQ_HANDLER(142) \
    DECLARE_IRQ_HANDLER(143) \
    DECLARE_IRQ_HANDLER(144) \
    DECLARE_IRQ_HANDLER(145) \
    DECLARE_IRQ_HANDLER(146) \
    DECLARE_IRQ_HANDLER(147) \
    DECLARE_IRQ_HANDLER(148) \
    DECLARE_IRQ_HANDLER(149) \
    DECLARE_IRQ_HANDLER(150) \
    DECLARE_IRQ_HANDLER(151) \
    DECLARE_IRQ_HANDLER(152) \
    DECLARE_IRQ_HANDLER(153) \
    DECLARE_IRQ_HANDLER(154) \
    DECLARE_IRQ_HANDLER(155) \
    DECLARE_IRQ_HANDLER(156) \
    DECLARE_IRQ_HANDLER(157) \
    DECLARE_IRQ_HANDLER(158) \
    DECLARE_IRQ_HANDLER(159) \
    DECLARE_IRQ_HANDLER(160) \
    DECLARE_IRQ_HANDLER(161) \
    DECLARE_IRQ_HANDLER(162) \
    DECLARE_IRQ_HANDLER(163) \
    DECLARE_IRQ_HANDLER(164) \
    DECLARE_IRQ_HANDLER(165) \
    DECLARE_IRQ_HANDLER(166) \
    DECLARE_IRQ_HANDLER(167) \
    DECLARE_IRQ_HANDLER(168) \
    DECLARE_IRQ_HANDLER(169) \
    DECLARE_IRQ_HANDLER(170) \
    DECLARE_IRQ_HANDLER(171) \
    DECLARE_IRQ_HANDLER(172) \
    DECLARE_IRQ_HANDLER(173) \
    DECLARE_IRQ_HANDLER(174) \
    DECLARE_IRQ_HANDLER(175) \
    DECLARE_IRQ_HANDLER(176) \
    DECLARE_IRQ_HANDLER(177) \
    DECLARE_IRQ_HANDLER(178) \
    DECLARE_IRQ_HANDLER(179) \
    DECLARE_IRQ_HANDLER(180) \
    DECLARE_IRQ_HANDLER(181) \
    DECLARE_IRQ_HANDLER(182) \
    DECLARE_IRQ_HANDLER(183) \
    DECLARE_IRQ_HANDLER(184) \
    DECLARE_IRQ_HANDLER(185) \
    DECLARE_IRQ_HANDLER(186) \
    DECLARE_IRQ_HANDLER(187) \
    DECLARE_IRQ_HANDLER(188) \
    DECLARE_IRQ_HANDLER(189) \
    DECLARE_IRQ_HANDLER(190) \
    DECLARE_IRQ_HANDLER(191) \
    DECLARE_IRQ_HANDLER(192) \
    DECLARE_IRQ_HANDLER(193) \
    DECLARE_IRQ_HANDLER(194) \
    DECLARE_IRQ_HANDLER(195) \
    DECLARE_IRQ_HANDLER(196) \
    DECLARE_IRQ_HANDLER(197) \
    DECLARE_IRQ_HANDLER(198) \
    DECLARE_IRQ_HANDLER(199) \
    DECLARE_IRQ_HANDLER(200) \
    DECLARE_IRQ_HANDLER(201) \
    DECLARE_IRQ_HANDLER(202) \
    DECLARE_IRQ_HANDLER(203) \
    DECLARE_IRQ_HANDLER(204) \
    DECLARE_IRQ_HANDLER(205) \
    DECLARE_IRQ_HANDLER(206) \
    DECLARE_IRQ_HANDLER(207) \
    DECLARE_IRQ_HANDLER(208) \
    DECLARE_IRQ_HANDLER(209) \
    DECLARE_IRQ_HANDLER(210) \
    DECLARE_IRQ_HANDLER(211) \
    DECLARE_IRQ_HANDLER(212) \
    DECLARE_IRQ_HANDLER(213) \
    DECLARE_IRQ_HANDLER(214) \
    DECLARE_IRQ_HANDLER(215) \
    DECLARE_IRQ_HANDLER(216) \
    DECLARE_IRQ_HANDLER(217) \
    DECLARE_IRQ_HANDLER(218) \
    DECLARE_IRQ_HANDLER(219) \
    DECLARE_IRQ_HANDLER(220) \
    DECLARE_IRQ_HANDLER(221) \
    DECLARE_IRQ_HANDLER(222) \
    DECLARE_IRQ_HANDLER(223)

DECLARE_IRQ_HANDLERS();
void hal::IRQControllerManager::isr_setup() {
    IDT::get().set_handler(32, irq_handler_0);
    IDT::get().set_handler(33, irq_handler_1);
    IDT::get().set_handler(34, irq_handler_2);
    IDT::get().set_handler(35, irq_handler_3);
    IDT::get().set_handler(36, irq_handler_4);
    IDT::get().set_handler(37, irq_handler_5);
    IDT::get().set_handler(38, irq_handler_6);
    IDT::get().set_handler(39, irq_handler_7);
    IDT::get().set_handler(40, irq_handler_8);
    IDT::get().set_handler(41, irq_handler_9);
    IDT::get().set_handler(42, irq_handler_10);
    IDT::get().set_handler(43, irq_handler_11);
    IDT::get().set_handler(44, irq_handler_12);
    IDT::get().set_handler(45, irq_handler_13);
    IDT::get().set_handler(46, irq_handler_14);
    IDT::get().set_handler(47, irq_handler_15);
    IDT::get().set_handler(48, irq_handler_16);
    IDT::get().set_handler(49, irq_handler_17);
    IDT::get().set_handler(50, irq_handler_18);
    IDT::get().set_handler(51, irq_handler_19);
    IDT::get().set_handler(52, irq_handler_20);
    IDT::get().set_handler(53, irq_handler_21);
    IDT::get().set_handler(54, irq_handler_22);
    IDT::get().set_handler(55, irq_handler_23);
    IDT::get().set_handler(56, irq_handler_24);
    IDT::get().set_handler(57, irq_handler_25);
    IDT::get().set_handler(58, irq_handler_26);
    IDT::get().set_handler(59, irq_handler_27);
    IDT::get().set_handler(60, irq_handler_28);
    IDT::get().set_handler(61, irq_handler_29);
    IDT::get().set_handler(62, irq_handler_30);
    IDT::get().set_handler(63, irq_handler_31);
    IDT::get().set_handler(64, irq_handler_32);
    IDT::get().set_handler(65, irq_handler_33);
    IDT::get().set_handler(66, irq_handler_34);
    IDT::get().set_handler(67, irq_handler_35);
    IDT::get().set_handler(68, irq_handler_36);
    IDT::get().set_handler(69, irq_handler_37);
    IDT::get().set_handler(70, irq_handler_38);
    IDT::get().set_handler(71, irq_handler_39);
    IDT::get().set_handler(72, irq_handler_40);
    IDT::get().set_handler(73, irq_handler_41);
    IDT::get().set_handler(74, irq_handler_42);
    IDT::get().set_handler(75, irq_handler_43);
    IDT::get().set_handler(76, irq_handler_44);
    IDT::get().set_handler(77, irq_handler_45);
    IDT::get().set_handler(78, irq_handler_46);
    IDT::get().set_handler(79, irq_handler_47);
	IDT::get().set_handler(80, irq_handler_48);
    IDT::get().set_handler(81, irq_handler_49);
    IDT::get().set_handler(82, irq_handler_50);
    IDT::get().set_handler(83, irq_handler_51);
    IDT::get().set_handler(84, irq_handler_52);
    IDT::get().set_handler(85, irq_handler_53);
    IDT::get().set_handler(86, irq_handler_54);
    IDT::get().set_handler(87, irq_handler_55);
    IDT::get().set_handler(88, irq_handler_56);
    IDT::get().set_handler(89, irq_handler_57);
    IDT::get().set_handler(90, irq_handler_58);
    IDT::get().set_handler(91, irq_handler_59);
    IDT::get().set_handler(92, irq_handler_60);
    IDT::get().set_handler(93, irq_handler_61);
    IDT::get().set_handler(94, irq_handler_62);
    IDT::get().set_handler(95, irq_handler_63);
    IDT::get().set_handler(96, irq_handler_64);
    IDT::get().set_handler(97, irq_handler_65);
    IDT::get().set_handler(98, irq_handler_66);
    IDT::get().set_handler(99, irq_handler_67);
    IDT::get().set_handler(100, irq_handler_68);
    IDT::get().set_handler(101, irq_handler_69);
    IDT::get().set_handler(102, irq_handler_70);
    IDT::get().set_handler(103, irq_handler_71);
    IDT::get().set_handler(104, irq_handler_72);
    IDT::get().set_handler(105, irq_handler_73);
    IDT::get().set_handler(106, irq_handler_74);
    IDT::get().set_handler(107, irq_handler_75);
    IDT::get().set_handler(108, irq_handler_76);
    IDT::get().set_handler(109, irq_handler_77);
    IDT::get().set_handler(110, irq_handler_78);
    IDT::get().set_handler(111, irq_handler_79);
    IDT::get().set_handler(112, irq_handler_80);
    IDT::get().set_handler(113, irq_handler_81);
    IDT::get().set_handler(114, irq_handler_82);
    IDT::get().set_handler(115, irq_handler_83);
    IDT::get().set_handler(116, irq_handler_84);
    IDT::get().set_handler(117, irq_handler_85);
    IDT::get().set_handler(118, irq_handler_86);
    IDT::get().set_handler(119, irq_handler_87);
    IDT::get().set_handler(120, irq_handler_88);
    IDT::get().set_handler(121, irq_handler_89);
    IDT::get().set_handler(122, irq_handler_90);
    IDT::get().set_handler(123, irq_handler_91);
    IDT::get().set_handler(124, irq_handler_92);
    IDT::get().set_handler(125, irq_handler_93);
    IDT::get().set_handler(126, irq_handler_94);
    IDT::get().set_handler(127, irq_handler_95);
	/// NOTE: Skip vector 128 since it's the syscalls vector
    IDT::get().set_handler(129, irq_handler_97);
    IDT::get().set_handler(130, irq_handler_98);
    IDT::get().set_handler(131, irq_handler_99);
    IDT::get().set_handler(132, irq_handler_100);
    IDT::get().set_handler(133, irq_handler_101);
    IDT::get().set_handler(134, irq_handler_102);
    IDT::get().set_handler(135, irq_handler_103);
    IDT::get().set_handler(136, irq_handler_104);
    IDT::get().set_handler(137, irq_handler_105);
    IDT::get().set_handler(138, irq_handler_106);
    IDT::get().set_handler(139, irq_handler_107);
    IDT::get().set_handler(140, irq_handler_108);
    IDT::get().set_handler(141, irq_handler_109);
    IDT::get().set_handler(142, irq_handler_110);
    IDT::get().set_handler(143, irq_handler_111);
    IDT::get().set_handler(144, irq_handler_112);
    IDT::get().set_handler(145, irq_handler_113);
    IDT::get().set_handler(146, irq_handler_114);
    IDT::get().set_handler(147, irq_handler_115);
    IDT::get().set_handler(148, irq_handler_116);
    IDT::get().set_handler(149, irq_handler_117);
    IDT::get().set_handler(150, irq_handler_118);
    IDT::get().set_handler(151, irq_handler_119);
    IDT::get().set_handler(152, irq_handler_120);
    IDT::get().set_handler(153, irq_handler_121);
    IDT::get().set_handler(154, irq_handler_122);
    IDT::get().set_handler(155, irq_handler_123);
    IDT::get().set_handler(156, irq_handler_124);
    IDT::get().set_handler(157, irq_handler_125);
    IDT::get().set_handler(158, irq_handler_126);
    IDT::get().set_handler(159, irq_handler_127);
    IDT::get().set_handler(160, irq_handler_128);
    IDT::get().set_handler(161, irq_handler_129);
    IDT::get().set_handler(162, irq_handler_130);
    IDT::get().set_handler(163, irq_handler_131);
    IDT::get().set_handler(164, irq_handler_132);
    IDT::get().set_handler(165, irq_handler_133);
    IDT::get().set_handler(166, irq_handler_134);
    IDT::get().set_handler(167, irq_handler_135);
    IDT::get().set_handler(168, irq_handler_136);
    IDT::get().set_handler(169, irq_handler_137);
    IDT::get().set_handler(170, irq_handler_138);
    IDT::get().set_handler(171, irq_handler_139);
    IDT::get().set_handler(172, irq_handler_140);
    IDT::get().set_handler(173, irq_handler_141);
    IDT::get().set_handler(174, irq_handler_142);
    IDT::get().set_handler(175, irq_handler_143);
    IDT::get().set_handler(176, irq_handler_144);
    IDT::get().set_handler(177, irq_handler_145);
    IDT::get().set_handler(178, irq_handler_146);
    IDT::get().set_handler(179, irq_handler_147);
    IDT::get().set_handler(180, irq_handler_148);
    IDT::get().set_handler(181, irq_handler_149);
    IDT::get().set_handler(182, irq_handler_150);
    IDT::get().set_handler(183, irq_handler_151);
    IDT::get().set_handler(184, irq_handler_152);
    IDT::get().set_handler(185, irq_handler_153);
    IDT::get().set_handler(186, irq_handler_154);
    IDT::get().set_handler(187, irq_handler_155);
    IDT::get().set_handler(188, irq_handler_156);
    IDT::get().set_handler(189, irq_handler_157);
    IDT::get().set_handler(190, irq_handler_158);
    IDT::get().set_handler(191, irq_handler_159);
    IDT::get().set_handler(192, irq_handler_160);
    IDT::get().set_handler(193, irq_handler_161);
    IDT::get().set_handler(194, irq_handler_162);
    IDT::get().set_handler(195, irq_handler_163);
    IDT::get().set_handler(196, irq_handler_164);
    IDT::get().set_handler(197, irq_handler_165);
    IDT::get().set_handler(198, irq_handler_166);
    IDT::get().set_handler(199, irq_handler_167);
    IDT::get().set_handler(200, irq_handler_168);
    IDT::get().set_handler(201, irq_handler_169);
    IDT::get().set_handler(202, irq_handler_170);
    IDT::get().set_handler(203, irq_handler_171);
    IDT::get().set_handler(204, irq_handler_172);
    IDT::get().set_handler(205, irq_handler_173);
    IDT::get().set_handler(206, irq_handler_174);
    IDT::get().set_handler(207, irq_handler_175);
    IDT::get().set_handler(208, irq_handler_176);
    IDT::get().set_handler(209, irq_handler_177);
    IDT::get().set_handler(210, irq_handler_178);
    IDT::get().set_handler(211, irq_handler_179);
    IDT::get().set_handler(212, irq_handler_180);
    IDT::get().set_handler(213, irq_handler_181);
    IDT::get().set_handler(214, irq_handler_182);
    IDT::get().set_handler(215, irq_handler_183);
    IDT::get().set_handler(216, irq_handler_184);
    IDT::get().set_handler(217, irq_handler_185);
    IDT::get().set_handler(218, irq_handler_186);
    IDT::get().set_handler(219, irq_handler_187);
    IDT::get().set_handler(220, irq_handler_188);
    IDT::get().set_handler(221, irq_handler_189);
    IDT::get().set_handler(222, irq_handler_190);
    IDT::get().set_handler(223, irq_handler_191);
	IDT::get().set_handler(224, irq_handler_192);
    IDT::get().set_handler(225, irq_handler_193);
    IDT::get().set_handler(226, irq_handler_194);
    IDT::get().set_handler(227, irq_handler_195);
    IDT::get().set_handler(228, irq_handler_196);
    IDT::get().set_handler(229, irq_handler_197);
    IDT::get().set_handler(230, irq_handler_198);
    IDT::get().set_handler(231, irq_handler_199);
    IDT::get().set_handler(232, irq_handler_200);
    IDT::get().set_handler(233, irq_handler_201);
    IDT::get().set_handler(234, irq_handler_202);
    IDT::get().set_handler(235, irq_handler_203);
    IDT::get().set_handler(236, irq_handler_204);
    IDT::get().set_handler(237, irq_handler_205);
    IDT::get().set_handler(238, irq_handler_206);
    IDT::get().set_handler(239, irq_handler_207);
    IDT::get().set_handler(240, irq_handler_208);
    IDT::get().set_handler(241, irq_handler_209);
    IDT::get().set_handler(242, irq_handler_210);
    IDT::get().set_handler(243, irq_handler_211);
    IDT::get().set_handler(244, irq_handler_212);
    IDT::get().set_handler(245, irq_handler_213);
    IDT::get().set_handler(246, irq_handler_214);
    IDT::get().set_handler(247, irq_handler_215);
    IDT::get().set_handler(248, irq_handler_216);
    IDT::get().set_handler(249, irq_handler_217);
    IDT::get().set_handler(250, irq_handler_218);
    IDT::get().set_handler(251, irq_handler_219);
    IDT::get().set_handler(252, irq_handler_220);
    IDT::get().set_handler(253, irq_handler_221);
    IDT::get().set_handler(254, irq_handler_222);
    IDT::get().set_handler(255, irq_handler_223);
}

/// IRQ handler is here since it needs to be compiled with -mgeneral-regs-only
void hal::IRQControllerManager::irq_handler(size_t irqline) {
	auto controller = find_controller(irqline);
	if(controller) controller->interrupt_handler(irqline);
}